import "./style.css";
// import { main as cargoActions } from "./cargo.js";

main();

function main() {
  const debugText = document.querySelector("#debugText")!;
  const debugBtn = document.querySelector("#debugBtn")!;

  // const app = document.querySelector<HTMLDivElement>("#app")!;
  const vignettesContainer =
    document.querySelector<HTMLDivElement>(".vignettes")!;

  const intersection = document.querySelector(".intersection")!;

  const vignetteElements = addElements(vignettesContainer);

  /* Mirrored Cargo setup past this point */

  // cargoActions();

  /* Not for Cargo */

  // debugBtn.addEventListener("click", (_) => {
  //   io.takeRecords();
  // });
}

function addElements(container: Element) {
  const vignettePaths = [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
  ];

  vignettePaths.forEach((path, i) => {
    const elem = document.createElement("div");
    // use linked class as that's generated by Cargo
    elem.innerHTML += `
      <div id="${++i} "class="vignette linked">
        <img src="/images/${path}">
      </div>
    `;
    container.append(elem);
  });
}
